### ISSUE TITLE
Icons do not appear

### ISSUE THREAD

**Issue by MrKuip** [nreese/kibana-time-plugin#52]
I installed the kibana-time-plugin succesfully but the icons in the time-animation panel do not appear.
Any idea where to look?

**Comment by AbdessamadM** [comment]
Hello,
Same thing for me, any help would be appreciated

**Comment by nreese** [comment]
Which version of Kibana are using?

**Comment by AbdessamadM** [comment]
version : 6.6.2
for that I use master branch

**Comment by MrKuip** [comment]
I,m using 6.6.2

**Comment by reaisinc** [comment]
Same problem with 6.5.4 when building as oss.  Fixed by globally replacing instances of "glyphicon" to "fa".  Change glyphicon-chevron-left/right/play/pause to fa-backward/forward/play/pause in carousel.less and bootstrap-addons.js.  Also changed time.css to increase the height of the buttons to 18px:

```
.time-vis {
  .btn {
    color: #F6F6F6;
    height:18px;
  }
...
```

**Comment by AbdessamadM** [comment]
Solved :  
1. By replacing 'glyphicon' to 'fa' in whole project.
2. Clear cache after with this command : npm cache clear --force

**Comment by AbdessamadM** [comment]
Solved :
1. By replacing 'glyphicon' to 'fa' in whole project.
2. Clear cache after with this command : _npm cache clear --force_
    [https://stackoverflow.com/questions/36985240/how-to-clear-the-cache-in-angularjs](url)

**Comment by imabaharin** [comment]
Hello, 
The same things happen to me. I am using version 7.3.0.
I am already do the steps above but the icon still missing. 
Is it because of different version??
